/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package the.guardian.api.kotlin.client

import the.guardian.api.kotlin.http.ContentResponse
import kotlin.test.Test
import kotlin.test.assertEquals

class ContentApiTest {
    @Test fun testGetContent() {
        val contentResponse: ContentResponse? = null
        val contentApiTest = ContentApi("9cb97729-b42b-4c0a-832a-84cc03c43841")
        assertEquals(contentApiTest.content().setQuery("12 years a slave")
        .setTag("film/film,tone/reviews")
        .setFromDate("2010-07-20")
        .setShowTags("contributor")
        .setShowFields("starRating,headline,thumbnail,short-url")
        .setOrderBy("relevance").fetch(), contentResponse)
    }
}
