/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package the.guardian.api.kotlin.client

import the.guardian.api.kotlin.http.editions.EditionsResponse
import kotlin.test.Test
import kotlin.test.assertEquals

class GuardianApiTest {
//    @Test fun testGetContent() {
//        val contentResponse: SingleItemResponse? = null
//        val contentApiTest = GuardianApi("9cb97729-b42b-4c0a-832a-84cc03c43841")
//        assertEquals(contentApiTest.content().setQuery("12 years a slave")
//        .setTag("film/film,tone/reviews")
//        .setFromDate("2023-03-20")
//        .setShowTags("contributor")
//        .setShowFields("starRating,headline,thumbnail,short-url")
//        .setOrderBy("relevance").fetch(), contentResponse)
//    }

//    @Test fun testGetTags() {
//        val tagsResponse: EditionsResponse? = null
//        val contentApiTest = GuardianApi("9cb97729-b42b-4c0a-832a-84cc03c43841")
//        assertEquals(contentApiTest.tags().setQuery("apple")
//            .setSection("technology")
//            .setShowReferences("all").fetch(), tagsResponse)
//    }

//    @Test fun testGetSections() {
//        val sectionsResponse: SectionsResponse? = null
//        val contentApiTest = GuardianApi("9cb97729-b42b-4c0a-832a-84cc03c43841")
//        assertEquals(contentApiTest.sections().setQuery("business").fetch(), sectionsResponse)
//    }

    @Test fun testGetEditions() {
        val editionsResponse: EditionsResponse? = null
        val guardianApiTest = GuardianApi("9cb97729-b42b-4c0a-832a-84cc03c43841")
        assertEquals(guardianApiTest.editions().setQuery("uk").fetch(), editionsResponse)
    }
}
