/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package the.guardian.api.client

import org.junit.jupiter.api.BeforeEach
import kotlin.test.Test

class GuardianApiTest {
    private lateinit var guardianApi: the.guardian.api.client.GuardianApi
    @BeforeEach
    fun setUp() {
        guardianApi = the.guardian.api.client.GuardianApi("9cb97729-b42b-4c0a-832a-84cc03c43841")
    }
    @Test fun testGetContent() {

        val contentResponse = this.guardianApi.content().setQuery("12 years a slave")
        .setTag("film/film,tone/reviews")
        .setFromDate("2023-03-20")
        .setShowTags("contributor")
        .setShowFields("starRating,headline,thumbnail,short-url")
        .setOrderBy("relevance").fetch()

        println(contentResponse)
    }

    @Test fun testGetTags() {
        val tagsResponse = this.guardianApi.tags().setQuery("apple")
            .setSection("technology")
            .setShowReferences("all").fetch()

        println(tagsResponse)
    }

    @Test fun testGetSections() {
        val sectionsResponse = this.guardianApi.sections().setQuery("business").fetch()

        println(sectionsResponse)
    }

    @Test fun testGetEditions() {
        val editionsResponse = this.guardianApi.editions().setQuery("uk").fetch()

        println(editionsResponse)
    }

    @Test fun testGetSingleItem() {
        val singleItemResponse= this.guardianApi.singleItem().setId("/sport/2022/oct/07/cricket-jos-buttler-primed-for-england-comeback-while-phil-salt-stays-focused")
        .setShowStoryPackage(true)
        .setShowEditorsPicks(true)
        .setShowMostViewed(true)
        .setShowRelated(true).fetch()

        println(singleItemResponse)
    }
}
